### ISSUE TITLE
Column Data Types When Storing Address Ranges

### ISSUE THREAD

**Issue by broberts-mrmc** [mlocati/ip-lib#34]
Question...

The Readme.md mentions storing an address range in a database such as MySQL or MariaDB using three columns (i.e. `addressType`, `rangeFrom`, `rangeTo`) so that a simple query can be used to check whether a given address is in a given range.

What data types should be used for the `rangeFrom` and `rangeTo` columns so that the query performs as expected (i.e. yields the correct results)? Just a string type with a length capable of storing IPv4 and IPv6 string representations including delimiters? `VARCHAR(39)`?

```
/*
 * Let's assume that:
 * - $pdo is a PDO instance
 * - $range is a range object
 * - $address is an address object
 */

// Save the $range object
$insertQuery = $pdo->prepare('
    insert into ranges (addressType, rangeFrom, rangeTo)
    values (:addressType, :rangeFrom, :rangeTo)
');
$insertQuery->execute(array(
    ':addressType' => $range->getAddressType(),
    ':rangeFrom' => $range->getComparableStartString(),
    ':rangeTo' => $range->getComparableEndString(),
));

// Retrieve the saved ranges where an address $address falls:
$searchQuery = $pdo->prepare('
    select * from ranges
    where addressType = :addressType
    and :address between rangeFrom and rangeTo
');
$searchQuery->execute(array(
    ':addressType' => $address->getAddressType(),
    ':address' => $address->getComparableString(),
));
$rows = $searchQuery->fetchAll();
$searchQuery->closeCursor();
```

**Comment by mlocati** [comment]
For the `rangeFrom` and `rangeTo` columns, for performance and storage optimizations I'd use:
- `VARCHAR(39)` if you use both IPv4 and IPv6 addtesses
- `CHAR(15)` if you only use IPv4 addresses
- `CHAR(39)` if you only use IPv6 addresses
- the two columns should have the `ascii_bin` collation
- you should have an index with the two columns

I'd also avoid using the `addressType` column since it's superfluous (I'll update the readme accordingly).
